"""Regenerate standalone notebooks from the current fronttrack source.

Run with the project's Python environment. The readable embedded source is a
fallback for Colab / a downloaded notebook; local checkouts use src/ instead.
Execution outputs are generated separately with tools/check_notebooks.py.
"""
from pathlib import Path
import copy
import hashlib
import json
import textwrap

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {p.name: p.read_text() for p in sorted((ROOT/'src/fronttrack').glob('*.py'))}
DIGEST = hashlib.sha256(json.dumps(SOURCES, sort_keys=True).encode()).hexdigest()


def md(s):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': textwrap.dedent(s).strip()+'\n'}


def code(s, *, hidden=False):
    return {'cell_type': 'code', 'execution_count': None, 'outputs': [],
            'metadata': {'jupyter': {'source_hidden': True}, 'cellView': 'form'} if hidden else {},
            'source': textwrap.dedent(s).strip()+'\n'}


setup = code('''
# Install only missing dependencies into this notebook's Python environment.
import sys, subprocess, importlib.util
if sys.version_info < (3, 10):
    raise RuntimeError("Use Python 3.10 or newer")
requirements = {"numpy": "numpy>=1.24", "matplotlib": "matplotlib>=3.7",
                "ipywidgets": "ipywidgets>=8,<9"}
missing = [spec for name, spec in requirements.items() if importlib.util.find_spec(name) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
if "google.colab" in sys.modules:
    from google.colab import output
    output.enable_custom_widget_manager()
%matplotlib inline
''')
bootstrap = code('''
# Standalone source snapshot. Generated by tools/build_notebooks.py; do not edit here.
from pathlib import Path
import tempfile, hashlib, json
BUNDLED_SOURCES = '''+repr(SOURCES)+'''
SOURCE_SHA256 = '''+repr(DIGEST)+'''
assert hashlib.sha256(json.dumps(BUNDLED_SOURCES, sort_keys=True).encode()).hexdigest() == SOURCE_SHA256
local_src = next((p / "src" for p in (Path.cwd(), *Path.cwd().parents)
                  if (p / "src/fronttrack/visualization.py").is_file()), None)
if "fronttrack" not in sys.modules:
    if local_src is not None:
        sys.path.insert(0, str(local_src))
    else:
        _bundle_directory = tempfile.TemporaryDirectory(prefix="fronttrack-notebook-")
        package = Path(_bundle_directory.name) / "fronttrack"
        package.mkdir()
        for name, source in BUNDLED_SOURCES.items():
            (package / name).write_text(source)
        sys.path.insert(0, _bundle_directory.name)
import fronttrack
print("Source:", "local checkout" if local_src else "bundled notebook snapshot")
print("Bundled source fingerprint:", SOURCE_SHA256[:16])
''', hidden=True)
imports = code('''
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display
from fronttrack import DiscreteFlux, FrontTracker
from fronttrack.visualization import (observe_tracker, plot_profile, plot_spacetime,
                                     color_norm, dashboard, step_profile)
''')
intro = '''
**Run all cells from top to bottom.** In Jupyter choose **Run → Run All Cells**;
in Colab choose **Runtime → Run all**. No account credentials, repository clone,
or file upload beyond this notebook is needed. Initial setup installs missing
NumPy, Matplotlib and ipywidgets. A CPU runtime is sufficient.

Each notebook carries a readable snapshot of the solver for standalone use.
Inside a local project checkout it uses `src/fronttrack` instead. Restart the
kernel/runtime after changing solver versions. GitHub displays saved figures;
open the notebook in Jupyter or Colab to use its controls.
'''
math = r'''
We solve $u_t+(f_h(u))_x=0$ on $\mathbb R$, where $f_h$ interpolates the supplied
flux at the state nodes. Front speeds come from Rankine–Hugoniot and the scalar
entropy envelope. Colours encode the **physical value of $u$**, with one fixed
scale across the run; thin lines trace fronts. Rarefactions are staircases for
$f_h$, not smooth fans. The space–time colour background samples the solution
in space and time; the overlaid paths and saved profile jumps use actual front
geometry. A finer display raster does not improve the numerical approximation.

The chosen $x$ interval is an **observation window**, not a bounded PDE domain.
The first and last initial states extend to infinity. Use Compact Domain Schemes
for periodic domains. This notebook does not impose inflow or wall conditions.
'''
parameters = code('''
# EDIT THIS CELL, then rerun the cells below it.
def f(u):
    """Your flux: vectorized NumPy input, finite output of matching shape."""
    return 0.5 * u**2
    # Alternatives: u**3; u*(1-u); np.sin(u); 0.5*u**2 + 0.1*np.sin(3*u)

# Numerical state grid. Include every initial value for exact representation.
u_grid = np.linspace(-1.0, 1.0, 81)

# N jump positions need N+1 region values, including both infinite exterior regions.
positions = [0.0, 1.0]
values = [0.0, 1.0, 0.0]

# Observation window and end time (no imposed boundary conditions).
x_window = (-1.0, 3.0)
T = 3.0
snapshot_times = [0.0, 1.0, 2.0, 3.0]

# Display resolution only; state nodes / initial jump locations control approximation.
space_samples = 601
time_frames = 101
cmap = "viridis"  # alternatives: cividis, coolwarm, magma
''')
run = code('''
flux = DiscreteFlux(f, u_grid)
if not np.isfinite(T) or T <= 0:
    raise ValueError("T must be positive and finite")
if len(x_window) != 2 or not np.isfinite(x_window).all() or x_window[0] >= x_window[1]:
    raise ValueError("Use a finite, increasing observation window")
if any(isinstance(n, bool) or not isinstance(n, (int, np.integer)) or n < 2
       for n in (space_samples, time_frames)):
    raise ValueError("space_samples and time_frames must be integers >= 2")
snapshot_times = np.asarray(snapshot_times, dtype=float)
if snapshot_times.ndim != 1 or not len(snapshot_times) or not np.isfinite(snapshot_times).all() \\
        or np.any((snapshot_times < 0) | (snapshot_times > T)):
    raise ValueError("snapshot_times must be a nonempty list of finite times in [0,T]")

def make_tracker():
    return FrontTracker.from_values(flux, positions, values, max_events=100000)

tracker = make_tracker()
quantized = flux.u_grid[flux.state_index(values)]
print("Input values:    ", np.asarray(values))
print("Values evolved:  ", quantized)
print("Maximum quantization change:", float(np.max(np.abs(quantized-values))))
x = np.linspace(*x_window, space_samples)
times = np.unique(np.r_[np.linspace(0, T, time_frames), snapshot_times])
history = observe_tracker(tracker, x, times)
norm = color_norm(history)
print(f"Completed t={tracker.time:g}: {tracker.event_count} collision clusters; {len(tracker.fronts)} fronts")
''')
flux_plot = code('''
u = np.linspace(u_grid[0], u_grid[-1], 1001)
fig, ax = plt.subplots(figsize=(7, 3))
ax.plot(u, np.broadcast_to(f(u), u.shape), label="Supplied flux f", linewidth=2)
ax.plot(flux.u_grid, flux.f_values, ".--", label="Polygonal flux f_h", markersize=3)
ax.set(xlabel="u", ylabel="Flux", title="The flux that is actually evolved")
ax.legend()
plt.show()
''')
static = code('''
fig, axes = plt.subplots(1, 2, figsize=(11, 4), constrained_layout=True)
plot_profile(history, -1, ax=axes[0], cmap=cmap, norm=norm)
plot_spacetime(history, ax=axes[1], cmap=cmap, norm=norm)
plt.show()
''')
snapshots = code('''
# Snapshots use the exact step boundaries, not the space-sampling grid.
fig, axes = plt.subplots(len(snapshot_times), 1, figsize=(8, 2.5*len(snapshot_times)),
                         constrained_layout=True, squeeze=False)
for ax, t in zip(axes[:, 0], snapshot_times):
    k = int(np.searchsorted(history.times, t))
    plot_profile(history, k, ax=ax, cmap=cmap, norm=norm)
plt.show()
''')
playground = [md('# Front tracking playground\n\nChoose a flux, initial data and observation window, then explore the moving fronts.'),
              md(intro), setup, bootstrap, imports, md('## What the pictures mean\n'+math),
              md('## 1. Define your experiment\nEdit the function and parameters below. Initial values outside the state grid are rejected; off-node values are rounded to the nearest node.'), parameters,
              md('To use a sampled smooth profile, replace `positions` and `values` in the cell above with the following, then rerun below. The exterior values are still supplied explicitly.\n\n```python\nedges = np.linspace(-1, 1, 51)\ncenters = (edges[:-1] + edges[1:]) / 2\npositions = edges\nvalues = np.r_[0.0, np.exp(-8*centers**2), 0.0]\n```\n\nThese are midpoint samples, not exact cell averages. Refine both the initial partition and state grid to study convergence.'),
              md('## 2. Run and inspect the flux'), run, flux_plot,
              md('## 3. Space–time diagram and profile'), static,
              md('## 4. Move through time\nThe slider selects a saved time. Play advances through the saved frames; all controls reuse the completed calculation.'),
              code('viewer = dashboard(history, cmap=cmap)\ndisplay(viewer)'),
              md('## 5. Profile snapshots'), snapshots,
              md('### An additional time of your choice\nThis cell independently evolves a fresh tracker to the requested time, so it can go backwards or choose a time absent from the slider.'),
              code('''
requested_time = 1.375  # EDIT; any finite nonnegative time
one = observe_tracker(make_tracker(), x, [requested_time])
plot_profile(one, cmap=cmap, norm=color_norm(np.r_[norm.vmin, norm.vmax, one.profiles[0][1]]))
plt.show()
'''), md('## 6. Save figures and numerical samples\nFiles are written in the notebook’s working directory. In Colab use the Files panel to download them. Repeating this cell replaces these named export files.'),
              code('''
output_dir = Path("front_tracking_exports")
output_dir.mkdir(exist_ok=True)
fig, ax = plt.subplots(figsize=(8, 5), constrained_layout=True)
plot_spacetime(history, ax=ax, cmap=cmap, norm=norm)
fig.savefig(output_dir / "spacetime.png", dpi=180)
fig.savefig(output_dir / "spacetime.pdf")
plt.close(fig)
np.savez_compressed(output_dir / "solution.npz", x=history.x, times=history.times,
                    u=history.values, u_grid=flux.u_grid, f_values=flux.f_values,
                    segments=np.asarray(history.segments).reshape(-1, 4))
for k, t in enumerate(snapshot_times):
    fig, ax = plt.subplots(figsize=(7, 3), constrained_layout=True)
    plot_profile(history, int(np.searchsorted(history.times, t)), ax=ax, cmap=cmap, norm=norm)
    fig.savefig(output_dir / f"profile_{k:02d}.png", dpi=160)
    plt.close(fig)
print("Exports:", output_dir)
'''), md('## Experiments worth trying\n- Set `f(u)=u` to see translation without deformation.\n- Use Burgers data `[1, 0, -1]` at `[-0.5, 0.5]`: two shocks merge at $(x,t)=(0,1)$.\n- Use `f(u)=u**3` with one jump from $-1$ to $1$: inspect the compound wave.\n- Halve the state spacing while leaving display resolution fixed. Then increase only display resolution. These are different experiments.\n\nThe algorithm scans adjacent fronts at every interaction. Large state grids or many initial jumps can be expensive; begin with these modest settings.')]

gallery = [md('# Front tracking: four experiments ready to run\n\nA Burgers pulse, merging shocks, a rarefaction and a nonconvex compound wave.'), md(intro),
           setup, bootstrap, imports, md('## Reading the diagrams\n'+math),
           md('## Run the four experiments\nNo input is required. The pulse’s rarefaction meets its shock at $t=2$; the two collision shocks meet at $(0,1)$. The rarefaction and compound wave illustrate the state-grid staircase.'),
           code('''
cases = {
    "Burgers pulse": (lambda u: .5*u**2, [0, 1], [0, 1, 0], (-1, 3), 3.0),
    "Merging shocks": (lambda u: .5*u**2, [-.5, .5], [1, 0, -1], (-1.5, 1.5), 2.0),
    "Burgers rarefaction": (lambda u: .5*u**2, [0], [-1, 1], (-2, 2), 1.5),
    "Nonconvex compound wave": (lambda u: u**3, [0], [-1, 1], (-1, 5), 1.5),
}
experiments = {}
for name, (f, jumps, states, window, end_time) in cases.items():
    flux = DiscreteFlux(f, np.linspace(-1, 1, 81))
    tracker = FrontTracker.from_values(flux, jumps, states)
    experiments[name] = observe_tracker(tracker, np.linspace(*window, 601),
                                        np.linspace(0, end_time, 101))
    print(f"{name}: completed t={tracker.time:g}, {tracker.event_count} collision clusters")
'''), md('## Gallery\nStatic previews are saved for GitHub readers.'),
           code('''
fig, axes = plt.subplots(2, 2, figsize=(11, 9), constrained_layout=True)
for ax, (name, h) in zip(axes.flat, experiments.items()):
    plot_spacetime(h, ax=ax)
    ax.set_title(name)
plt.show()
'''), md('## Interactive explorer\nChoose an experiment, then move the time slider or press Play. Colours keep the same meaning throughout each experiment.'),
           code('''
selector = widgets.Dropdown(options=list(experiments), description="Experiment",
                           style={"description_width": "initial"}, layout=widgets.Layout(width="400px"))
viewer_box = widgets.VBox()
def select_experiment(change=None):
    for old in viewer_box.children:
        old.close()
    viewer_box.children = (dashboard(experiments[selector.value]),)
selector.observe(select_experiment, names="value")
select_experiment()
display(widgets.VBox([selector, viewer_box]))
'''), md('## Profile snapshots\nChange the experiment name or snapshot fractions and rerun this cell. Profiles use actual front locations at the nearest saved times; each title gives the time displayed.'),
           code('''
experiment_name = "Burgers pulse"
snapshot_fractions = [0.0, 1/3, 2/3, 1.0]
h = experiments[experiment_name]
if not len(snapshot_fractions) or not np.isfinite(snapshot_fractions).all() \\
        or np.any((np.asarray(snapshot_fractions) < 0) | (np.asarray(snapshot_fractions) > 1)):
    raise ValueError("Snapshot fractions must lie in [0,1]")
fig, axes = plt.subplots(len(snapshot_fractions), 1, figsize=(8, 2.5*len(snapshot_fractions)),
                         constrained_layout=True, squeeze=False)
for ax, fraction in zip(axes[:, 0], snapshot_fractions):
    k = int(np.argmin(abs(h.times - fraction*h.times[-1])))
    plot_profile(h, k, ax=ax)
fig.suptitle(experiment_name)
plt.show()
'''), md('## Export the selected experiment\nExports the currently selected dropdown experiment. Repeating the cell replaces the named files.'),
           code('''
h = experiments[selector.value]
output_dir = Path("front_tracking_exports")
output_dir.mkdir(exist_ok=True)
fig, ax = plt.subplots(figsize=(8, 5), constrained_layout=True)
plot_spacetime(h, ax=ax)
ax.set_title(selector.value)
fig.savefig(output_dir / "demo_spacetime.png", dpi=180)
plt.close(fig)
np.savez_compressed(output_dir / "demo_solution.npz", x=h.x, times=h.times, u=h.values,
                    segments=np.asarray(h.segments).reshape(-1, 4))
print("Exports:", output_dir)
'''), md('For your own flux, states, snapshot times and observation window, open **01_front_tracking_playground.ipynb**. These are scalar homogeneous Cauchy experiments, not simulations of systems or imposed boundaries.')]

for filename, cells in [('01_front_tracking_playground.ipynb', playground),
                        ('02_ready_to_run_examples.ipynb', gallery)]:
    cells = copy.deepcopy(cells)
    for k, cell in enumerate(cells):
        cell['id'] = f'cell-{k:03d}'
        cell['source'] = cell['source'].splitlines(keepends=True)
    notebook = {'nbformat': 4, 'nbformat_minor': 5, 'cells': cells,
                'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
                             'language_info': {'name': 'python', 'version': '3.12'},
                             'colab': {'name': filename, 'toc_visible': True},
                             'fronttrack_source_sha256': DIGEST}}
    target = ROOT/'notebooks'/filename
    target.write_text(json.dumps(notebook, indent=1)+'\n')
    print(target)
